// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var example = "\n{\n  \"base-url\": \"https://pagure.io\",\n  \"type\": \"pagure\",\n  \"name\": \"pagure.io\"\n}\n";

function parseConnection(json) {
  return {
          name: Json_decode.field("name", Json_decode.string, json),
          connection_type: Json_decode.field("type", Json_decode.string, json),
          base_url: Json_decode.optional((function (param) {
                  return Json_decode.field("base-url", Json_decode.string, param);
                }), json)
        };
}

function runExample(param) {
  console.log("Running connection example");
  var json = Json.parseOrRaise(example);
  var connections = parseConnection(json);
  console.log(connections);
  
}

exports.example = example;
exports.parseConnection = parseConnection;
exports.runExample = runExample;
/* No side effect */
