// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function parse(json) {
  return {
          name: Json_decode.field("name", Json_decode.string, json),
          connection_type: Json_decode.field("type", Json_decode.string, json),
          base_url: Json_decode.optional((function (param) {
                  return Json_decode.field("base-url", Json_decode.string, param);
                }), json)
        };
}

exports.parse = parse;
/* No side effect */
