// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Tenant = require("./Tenant.bs.js");
var Project = require("./Project.bs.js");
var Resources = require("./Resources.bs.js");
var Connection = require("./Connection.bs.js");

Project.runExample(undefined);

Connection.runExample(undefined);

Tenant.runExample(undefined);

Resources.runExample(undefined);

/*  Not a pure module */
