// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Util = require("./Util.bs.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function decodeSourceRepositoryDict(name, json) {
  return {
          name: name,
          connection: Json_decode.optional((function (param) {
                  return Json_decode.field("connection", Json_decode.string, param);
                }), json)
        };
}

function decodeSourceRepository(json) {
  var dict = Js_json.decodeObject(json);
  if (dict === undefined) {
    return {
            name: Json_decode.string(json),
            connection: undefined
          };
  }
  var match = Belt_List.fromArray(Js_dict.entries(Caml_option.valFromOption(dict)));
  if (!match) {
    return Util.decodeFail("SourceRepository dictionary can only contain one value");
  }
  if (match.tl) {
    return Util.decodeFail("SourceRepository dictionary can only contain one value");
  }
  var match$1 = match.hd;
  return decodeSourceRepositoryDict(match$1[0], match$1[1]);
}

function parse(json) {
  return {
          name: Json_decode.field("name", Json_decode.string, json),
          description: Json_decode.field("description", Json_decode.string, json),
          tenant: Json_decode.optional((function (param) {
                  return Json_decode.field("tenant", Json_decode.string, param);
                }), json),
          connection: Json_decode.optional((function (param) {
                  return Json_decode.field("connection", Json_decode.string, param);
                }), json),
          website: Json_decode.optional((function (param) {
                  return Json_decode.field("website", Json_decode.string, param);
                }), json),
          documentation: Json_decode.optional((function (param) {
                  return Json_decode.field("documentation", Json_decode.string, param);
                }), json),
          issue_tracker_url: Json_decode.optional((function (param) {
                  return Json_decode.field("issue-tracker-url", Json_decode.string, param);
                }), json),
          review_dashboard: Json_decode.optional((function (param) {
                  return Json_decode.field("review-dashboard", Json_decode.string, param);
                }), json),
          mailing_lists: Json_decode.optional((function (param) {
                  return Json_decode.field("mailing-lists", (function (param) {
                                return Json_decode.list(Json_decode.string, param);
                              }), param);
                }), json),
          contacts: Json_decode.optional((function (param) {
                  return Json_decode.field("contacts", (function (param) {
                                return Json_decode.list(Json_decode.string, param);
                              }), param);
                }), json),
          source_repositories: Json_decode.field("source-repositories", (function (param) {
                  return Json_decode.list(decodeSourceRepository, param);
                }), json),
          options: Json_decode.optional((function (param) {
                  return Json_decode.field("options", (function (param) {
                                return Json_decode.list(Json_decode.string, param);
                              }), param);
                }), json)
        };
}

exports.decodeSourceRepositoryDict = decodeSourceRepositoryDict;
exports.decodeSourceRepository = decodeSourceRepository;
exports.parse = parse;
/* Util Not a pure module */
