// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function parse(json) {
  return {
          name: Json_decode.field("name", Json_decode.string, json),
          default_connection: Json_decode.optional((function (param) {
                  return Json_decode.field("default-connection", Json_decode.string, param);
                }), json),
          description: Json_decode.optional((function (param) {
                  return Json_decode.field("description", Json_decode.string, param);
                }), json),
          url: Json_decode.field("url", Json_decode.string, json)
        };
}

exports.parse = parse;
/* No side effect */
