// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var example = "\n  {\n    \"default-connection\": \"rdoproject.org\",\n    \"description\": \"The rdoproject.org tenant\",\n    \"tenant-options\": {\n        \"zuul/report-build-page\": true,\n        \"zuul/web-root\": \"https://review.rdoproject.org/zuul/\"\n    },\n    \"url\": \"https://review.rdoproject.org/manage\",\n    \"name\": \"rdoproject.org\"\n  }\n";

function parse(json) {
  return {
          name: Json_decode.field("name", Json_decode.string, json),
          default_connection: Json_decode.optional((function (param) {
                  return Json_decode.field("default-connection", Json_decode.string, param);
                }), json),
          description: Json_decode.optional((function (param) {
                  return Json_decode.field("description", Json_decode.string, param);
                }), json),
          url: Json_decode.field("url", Json_decode.string, json)
        };
}

function runExample(param) {
  console.log("Running tenant example");
  var json = Json.parseOrRaise(example);
  var connections = parse(json);
  console.log(connections);
  
}

exports.example = example;
exports.parse = parse;
exports.runExample = runExample;
/* No side effect */
