// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Tenant = require("../src/SF/Tenant.bs.js");

Jest.describe("Test resources JSON parsing", (function (param) {
        return Jest.test("parse tenant object", (function (param) {
                      var parsed_tenant = Tenant.parse(Json.parseOrRaise("\n  {\n    \"default-connection\": \"rdoproject.org\",\n    \"description\": \"The rdoproject.org tenant\",\n    \"tenant-options\": {\n        \"zuul/report-build-page\": true,\n        \"zuul/web-root\": \"https://review.rdoproject.org/zuul/\"\n    },\n    \"url\": \"https://review.rdoproject.org/manage\",\n    \"name\": \"rdoproject.org\"\n  }\n  "));
                      return Jest.Expect.toBe("rdoproject.org", Jest.Expect.expect(parsed_tenant.name));
                    }));
      }));

/*  Not a pure module */
